Repository nsmith5/rekor-sidekick, pull requests merged in 2022-01, with the labels that each got.

#4 Basic Rekor client implementation
  agent.go
  config.go
  etc/example-config.yaml
  go.mod
  go.sum
  main.go
  rekorclient.go
  rekorclient_test.go
  testdata/rekor-api-log-entry.json
  testdata/rekor-api-log.json
Labels: enhancement

#6 Add basic policy checking
  agent.go
  config.go
  etc/config.yaml
  etc/example-config.yaml
  go.mod
  go.sum
  policy.go
  policy_test.go
  rekor/client.go
  rekor/client_test.go
Labels: enhancement

#7 WIP: stdout output
  agent.go
  config.go
  etc/config.yaml
  main.go
  outputs/interface.go
  outputs/registry.go
  outputs/stdout/stdout.go
Labels: enhancement

#20 Add support for cloud events output
  README.md
  go.mod
  go.sum
  outputs/cloudevents/cloudevents.go
  outputs/cloudevents/cloudevents_test.go
Labels: enhancement

#24 outputs: add Pager Duty support
  README.md
  go.mod
  go.sum
  main.go
  outputs/pagerduty/pagerduty.go
Labels: enhancement

#27 E2E test using vaikas/sigstore-scaffolding and CloudEvents.
  .github/workflows/e2e.yml
  cmd/ce-sink/main.go
  go.mod
  go.sum
  hack/setup-kind.sh
  testdata/ce-receiver/ce-receiver.yaml
  testdata/rekor-sidekick/config.yaml
  testdata/rekor-sidekick/rekor-sidekick.yaml
Labels: testing

#36 Fix version command
  .goreleaser.yaml
Labels: bug
